name: IPNS Republish
permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  republish:
    strategy:
      fail-fast: false 
      matrix:
        environment: [dev, prod/bet, prod/network, prod/games, prod/io]
    name: Republish IPNS - ${{ matrix.environment }}
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check IPFS variable
        id: check
        run: |
          if [ "${{ vars.IPFS }}" = "true" ]; then
            echo "IPFS is enabled for ${{ matrix.environment }}, proceeding with IPNS republish"
          else
            echo "IPFS is disabled for ${{ matrix.environment }}, skipping IPNS republish"
            exit 0
          fi

      - name: Checkout
        if: ${{ vars.IPFS == 'true' }}
        uses: actions/checkout@v4

      - name: Republish IPNS record
        if: ${{ vars.IPFS == 'true' }}
        uses: betfinio/apps-republish-action@v1.0.0
        with:
          folder_name: '${{ vars.IPFS_FOLDER_NAME }}'
          ipns_private_key: ${{ secrets.IPNS_PRIVATE_KEY }}
          quicknode_api_key: ${{ secrets.QUICKNODE_API_KEY }}